name: Run Milky Bot

on:
  # 当有代码被推送到主分支时，自动运行此工作流
  push:
    branches:
      - main # 如果您的主分支是 master，请改为 master
  
  # 允许您在GitHub页面上手动点击按钮来运行
  workflow_dispatch:

# 赋予工作流读写仓库内容的权限，这是提交数据文件所必需的
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 第1步: "检出"代码，就是把您的仓库代码下载到临时的运行环境中
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步: 设置我们需要的Python版本
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 第3步: 安装 requirements.txt 中定义的所有Python库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 第4步: 运行您的Bot！
      # 这里会将您设置的Secrets作为环境变量传递给 bot.py 脚本
      - name: Run the bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          BOT_OWNER_ID: ${{ secrets.BOT_OWNER_ID }}
          BOT_PERSONA: ${{ secrets.BOT_PERSONA }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        run: python bot.py
